services:
  - type: web
    name: nobel-proposal-generator
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: APP_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.4
